import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import Input from "../../components/Input";

export default function Home() {
  const HOST_URL = process.env.HOST_URL || "http://localhost:3001";
  console.log(JSON.stringify(process.env))
  const [highlights, setHighlights] = useState<any[]>();

  const fetchHighlights = () => {
    axios
      .get(`${HOST_URL}/api/highlights`)
      ?.then((res) => setHighlights(res.data))
      ?.catch((err) => console.log(err));
  };

  const addHighlight = () => {
    // adds empty plaeholder
    axios
      .post(`${HOST_URL}/api/highlights/`, { highlight: "" })
      ?.then((res) => console.log(res))
      ?.catch((err) => console.log(err))
      ?.finally(() => {
        fetchHighlights();
      });
  };

  useEffect(() => {
    // fetch highlightd
    fetchHighlights();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: "30px" }}>
        <div style={{ display: "flex", justifyContent: "space-between" }}>
          <h2 style={{ color: "rgba(114, 97, 255, 1)" }}>
            Property highlights
          </h2>
          <div
            onClick={addHighlight}
            style={{
              userSelect: "none",
              cursor: "pointer",
              color: "white",
              outline: 0,
              border: "1px solid #7261FF",
              background: "#7261FF",
              borderRadius: "5px",
              padding: "8px 20px",
            }}
          >
            + Add highlight
          </div>
        </div>
          {highlights?.map((highlight) => (
            <Input
              key={highlight.id}
              highlight={highlight}
              highlights={highlights}
              setHighlights={setHighlights}
            />
          ))}
      </div>
    </>
  );
}
